import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mouseMemoirs = localFont({
  src: "./fonts/MouseMemoirs-Regular.woff2",
  variable: "--font-mouse-memoirs",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hangman Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mouseMemoirs.variable}>
        {children}
      </body>
    </html>
  );
}
